### ISSUE TITLE
Document the Nutrionix API

### ISSUE THREAD

**Issue by emoral435** [J-E-N-G-A/planet-foodies#4]

**Comment by anirudh-56** [comment]
Natural Language for Exercise (V2 / natural (exercise) 
Requires string description 
    - Optional weight (kg) - Optional height (cm) 
    - Optional age Response. 
returns in JSON object 
Useful Info: 
    - Metabolic Equivalent 
    - NF Calories (Estimated number of calories)
    - Compendium Code 
Natural Language for Nutrients 
Requires string description 
  - Optional number of servings 
  - Optional raw-num of foods 
Response: 
returns in JSON object 
Useful Info: 
  - Names of food ( filter out what's vegan, vegetation, Halal, allergy info)
  - Brand Names 
  - Calories 
  - Gluten Info 
  - Nutritional Info

**Comment by emoral435** [comment]
> Natural Language for Exercise (V2 / natural (exercise)

Just noticed that this was added, nice touch! Might move this to the Wiki

**Comment by emoral435** [comment]
Moved to the wiki 👍
